apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: travel
    component: travel-api-minio-volume
  name: minio-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi