FROM node:18.17-alpine as build

WORKDIR /app

COPY . .

RUN npm ci

RUN npm run build
RUN npm run build:server

FROM node:18.17-alpine

RUN adduser -D user
USER user

COPY --from=build /app/dist ./dist
COPY --from=build /app/distServer ./distServer
COPY --from=build /app/package.json ./package.json

CMD [ "npm", "run", "server:prod" ]