version: '3'
services:
  travel-static:
    image: travel-static:latest
    container_name: travel-static
    restart: always
    ports:
      - 3000:3000
    networks: 
      - local

networks:
  local: