apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: travel
    component: travel-static
  name: travel-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel
      component: travel-static
  template:
    metadata:
      labels:
        app: travel
        component: travel-static
    spec:
      containers:
        - image: travel-static:latest
          name: travel-static
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
