apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: travel
    component: travel-api-mq-volume
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
