apiVersion: v1
kind: Service
metadata:
  labels:
    app: travel
    component: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: rabbit
      port: 5672
      targetPort: 5672
    - name: rabbit-manager
      port: 15672
      targetPort: 15672
  selector:
    app: travel
    component: rabbitmq
