apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: travel
    component: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel
      component: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: travel
        component: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: password
            - name: RABBITMQ_DEFAULT_USER
              value: user
          image: rabbitmq:3.12-management
          name: rabbitmq
          ports:
            - containerPort: 5672
              hostPort: 5672
            - containerPort: 15672
              hostPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: travel-api-mq-volume
