// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package user

import (
	"time"
)

// NewUserDTO defines model for NewUserDTO.
type NewUserDTO struct {
	// Email user email
	Email string `json:"email" validate:"required,email"`

	// Name user name
	Name string `json:"name" validate:"required,gte=2"`

	// Password user password
	Password string `json:"password" validate:"required,gte=6"`

	// PasswordConfirm user password confirm
	PasswordConfirm string `json:"password_confirm" validate:"eqfield=Password"`
}

// UpdateUserDTO defines model for UpdateUserDTO.
type UpdateUserDTO struct {
	// Email user email
	Email *string `json:"email,omitempty" validate:"omitempty,email"`

	// Name user name
	Name *string `json:"name,omitempty" validate:"omitempty,gte=2"`

	// Password user password
	Password *string `json:"password,omitempty" validate:"omitempty,gte=6"`

	// PasswordConfirm user password confirm
	PasswordConfirm *string `json:"password_confirm,omitempty" validate:"eqfield=Password"`
}

// UserResponseDTO defines model for UserResponseDTO.
type UserResponseDTO struct {
	// DateCreated date created
	DateCreated time.Time `json:"date_created"`

	// Email user's email
	Email string `json:"email"`

	// Id user unique id
	ID string `json:"id"`

	// Name user's name
	Name string `json:"name"`
}

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody = NewUserDTO

// PutUserJSONRequestBody defines body for PutUser for application/json ContentType.
type PutUserJSONRequestBody = UpdateUserDTO
