FROM golang:1.20.6-alpine as build
ARG CONFIG_PATH

RUN mkdir /service

COPY go.* /service
WORKDIR /service
RUN go mod download

WORKDIR /service
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o cronjob \
  -ldflags="-X 'main.configPath=${CONFIG_PATH}'" \
  /service/cmd/cron/main.go 

FROM alpine:3.18.2

RUN adduser -D user
USER user

COPY --from=build /service/cronjob .
COPY --from=build /service/${CONFIG_PATH} /service/${CONFIG_PATH}

WORKDIR /service/

CMD ["./cronjob"]
