version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12:management
    container_name: rabbitmq
    ports:
      - "${MQ_PORT}:${RABBIT_PORT}"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks: 
      - local

volumes:
  rabbitmq_data:

networks:
  local:
