apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: travel
    component: travel-api
  name: travel-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel
      component: travel-api
  strategy: {}
  template:
    metadata:
      labels:
        app: travel
        component: travel-api
    spec:
      containers:
        - image: travel-api:latest
          name: travel-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8081
              hostPort: 8081
          livenessProbe:
            httpGet:
              path: /debug/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /debug/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          resources: {}
      restartPolicy: Always
