apiVersion: v1
kind: Service
metadata:
  labels:
    app: travel
    component: travel-api
  name: travel-api
spec:
  ports:
    - name: "api"
      port: 8080
      targetPort: 8080
    - name: "debug"
      port: 8081
      targetPort: 8081
  selector:
    app: travel
    component: travel-api
