// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package user

import (
	"time"
)

// DeleteUser defines model for DeleteUser.
type DeleteUser struct {
	// Password user password
	Password string `json:"password" validate:"required"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error error message
	Error  string             `json:"error"`
	Fields *map[string]string `json:"fields,omitempty"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	// Email user email
	Email string `json:"email" validate:"required,email"`

	// Name user name
	Name string `json:"name" validate:"required,gte=2"`

	// Password user password
	Password string `json:"password" validate:"required,gte=8"`

	// PasswordConfirm user password confirm
	PasswordConfirm string `json:"password_confirm" validate:"eqfield=Password"`
}

// UpdateUser defines model for UpdateUser.
type UpdateUser struct {
	// Email user email
	Email *string `json:"email,omitempty" validate:"omitempty,email"`

	// Name user name
	Name *string `json:"name,omitempty" validate:"omitempty,gte=2"`

	// Password user password
	Password string `json:"password" validate:"required"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// DateCreated date created
	DateCreated time.Time `json:"date_created"`

	// Email user's email
	Email string `json:"email"`

	// Id user unique id
	ID string `json:"id"`

	// Name user's name
	Name string `json:"name"`
}

// VerifyUser defines model for VerifyUser.
type VerifyUser struct {
	// Email user email
	Email string `json:"email" validate:"required,email"`

	// Token user verification token
	Token string `json:"token" validate:"required"`
}

// DeleteUsersJSONRequestBody defines body for DeleteUsers for application/json ContentType.
type DeleteUsersJSONRequestBody = DeleteUser

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = NewUser

// PutUsersJSONRequestBody defines body for PutUsers for application/json ContentType.
type PutUsersJSONRequestBody = UpdateUser

// PostUsersVerifyJSONRequestBody defines body for PostUsersVerify for application/json ContentType.
type PostUsersVerifyJSONRequestBody = VerifyUser
