kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # travel-api service
  - containerPort: 8080
    hostPort: 8080
  # travel-api debug
  - containerPort: 8081
    hostPort: 8081
  # travel-api metrics
  - containerPort: 8091
    hostPort: 8091
  # travel-static
  - containerPort: 3000
    hostPort: 3000
  # travel-api-db (postgres)
  - containerPort: 5432
    hostPort: 5432
  # travel-api-cache (redis)
  - containerPort: 6379
    hostPort: 6379
  # travel-api-mq
  - containerPort: 5672
    hostPort: 5672
  - containerPort: 15672
    hostPort: 15672
  # haproxy
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
  # loki
  - containerPort: 3100
    hostPort: 3100
  # grafana
  - containerPort: 4000
    hostPort: 4000
  # tempo
  - containerPort: 3101
    hostPort: 3101
  # minio
  - containerPort: 9000
    hostPort: 9000
  - containerPort: 9001
    hostPort: 9001

