apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: travel
    component: travel-grafana-storage
  name: grafana-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      pv-name: grafana-pv-label
  resources:
    requests:
      storage: 512Mi
