kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv
  labels:
    app: travel
    component: travel-grafana-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/grafana"
    type: DirectoryOrCreate
