// Package list provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package list

import (
	"time"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error error message
	Error  string             `json:"error"`
	Fields *map[string]string `json:"fields,omitempty"`
}

// Item defines model for Item.
type Item struct {
	// Address item address on map
	Address *string `json:"address,omitempty"`

	// DateCreated creation date
	DateCreated time.Time `json:"date_created"`

	// DateUpdated date of last update
	DateUpdated time.Time `json:"date_updated"`

	// Description item description
	Description *string `json:"description,omitempty"`

	// Id item id
	ID string `json:"id"`

	// ImageLinks array of attached image links
	ImageLinks *[]string `json:"image_links,omitempty"`

	// Links array of attached links
	Links *[]Link `json:"links,omitempty"`

	// ListId item parent id
	ListID string `json:"list_id"`

	// Name item name
	Name string `json:"name"`

	// Point item location on map
	Point Point `json:"point"`

	// Visited location is visited
	Visited bool `json:"visited"`
}

// Link link object
type Link struct {
	// Id link id
	ID string `json:"id"`

	// ItemId link parent id
	ItemID string `json:"item_id"`

	// Name link display name
	Name *string `json:"name,omitempty"`

	// Url url
	URL string `json:"url"`
}

// List defines model for List.
type List struct {
	// Completed is list completed
	Completed bool `json:"completed"`

	// DateCreated date of creation
	DateCreated time.Time `json:"date_created"`

	// DateUpdated date of last update
	DateUpdated *time.Time `json:"date_updated,omitempty"`

	// Description list description
	Description *string `json:"description,omitempty"`

	// Favorite is list favorite
	Favorite bool `json:"favorite"`

	// Id list id
	ID string `json:"id"`

	// ItemsId array of items ids
	ItemsID *[]string `json:"items_id,omitempty"`

	// Name list name
	Name string `json:"name"`

	// Private is list private
	Private bool `json:"private"`

	// UserId list owner id
	UserID string `json:"user_id"`
}

// Point item location on map
type Point struct {
	// Id location id
	ID string `json:"id"`

	// ItemId location parent id
	ItemID string `json:"item_id"`

	// Lat latitude of location on map
	Lat float64 `json:"lat"`

	// Lng longitude of location on map
	Lng float64 `json:"lng"`
}
