openapi: "3.0.0"
info:
  version: 1.0.0
  title: API
paths:
  /auth/login:
    post:
      tags: ["auth","post","login"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '201':
          description: user logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/refresh:
    post:
      tags: ["auth","post","refresh"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:

      responses:
        '201':
          description: token was refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/validate:
    post:
      tags: ["auth","post","validate"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:

      responses:
        '201':
          description: token was validated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/logout:
    post:
      tags: ["auth","post","logout"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:

      responses:
        '201':
          description: user logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/logout/all:
    post:
      tags: ["auth","post","logout","all"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:

      responses:
        '201':
          description: user logged out on all devices successfully
          content:
            application/json:
              schema:
                type: object
                properties:
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/password/change:
    post:
      tags: ["auth","post","change-password"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword'
      responses:
        '201':
          description: password is changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/password/reset:
    post:
      tags: ["auth","post","reset-password"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPassword'
      responses:
        '201':
          description: password reset request was handled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/password/reset/submit:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitResetPassword'
      responses:
        '201':
          description: password is changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
 
components:
  schemas:
    LoginUser:
      type: object
      properties:
        email:
          type: string
          description: "user email"
          x-oapi-codegen-extra-tags:
            validate: "required,email"
        password:
          type: string
          description: "user password"
          x-oapi-codegen-extra-tags:
            validate: "required"
      required:
        - email
        - password

    UserResponse:
      type: object
      properties:
        id:
          type: string
          description: user unique id
          x-go-name: ID
        name:
          type: string
          description: user's name
        email:
          type: string
          description: user's email
        date_created:    
          type: string
          description: date created
          x-go-type: time.Time
      required:
        - id
        - name
        - email
        - date_created

    ResetPassword:
      type: object
      properties:
        email:
          type: string
          description: "user email"
          x-oapi-codegen-extra-tags:
            validate: "required,email"
      required:
        - email

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: error message
        fields:
          type: object
          additionalProperties:
            type: string
      required:
        - error
    
    SubmitResetPassword:
      allOf:
        - $ref: '#/components/schemas/ResetToken'
        - $ref: '#/components/schemas/NewPassword'
    
    ChangePassword:
      allOf:
        - $ref: '#/components/schemas/OldPassword'
        - $ref: '#/components/schemas/NewPassword'

    OldPassword:
      type: object
      properties:
        password_old:
          type: string
          description: "user new password"
          x-oapi-codegen-extra-tags:
            validate: "required"
      required:
        - password_old

    NewPassword:
      type: object
      properties:
        password:
          type: string
          description: "user new password"
          x-oapi-codegen-extra-tags:
            validate: "required,gte=8"
        password_confirm:
          type: string
          description: "user new password confirm"
          x-oapi-codegen-extra-tags:
            validate: "eqfield=Password"
      required:
        - password
        - password_confirm

    ResetToken:
      type: object
      properties:
        token:
          type: string
          description: password reset secret token
          x-oapi-codegen-extra-tags:
            validate: "required"
      required:
        - token