openapi: "3.0.0"
info:
  version: 1.0.0
  title: API
paths:
  /lists:
    get:
      tags: ["lists","get"]
      responses:
        '200':
          description: get all lists of owner
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/List'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /lists/{id}:
    get:
      tags: ["lists","get"]
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the list
          schema:
            type: string
      responses:
        '200':
          description: returns a list with the specified ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/List'
        '404':
          description: list not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /lists/{list_id}/items:
    get:
      tags: ["items","get"]
      parameters:
        - name: list_id
          in: path
          required: true
          description: ID of the list
          schema:
            type: string
      responses:
        '200':
          description: get all items of the specified list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /lists/{list_id}/items/{item_id}:
    get:
      tags: ["items","get"]
      parameters:
        - name: list_id
          in: path
          required: true
          description: ID of the list
          schema:
            type: string
        - name: item_id
          in: path
          required: true
          description: ID of the item
          schema:
            type: string
      responses:
        '200':
          description: get an item with ID of the specified list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    List:
      type: object
      properties:
        id:
          type: string
          description: "list id"
          x-go-name: ID
        user_id:
          type: string
          description: "list owner id"
          x-go-name: UserID
        name:
          type: string
          description: "list name"
        description:
          type: string
          description: "list description"
        private:
          type: boolean
          description: "is list private"
        favorite:
          type: boolean
          description: "is list favorite"
        completed:
          type: boolean
          description: "is list completed"
        items_id:
          type: array
          description: "array of items ids"
          x-go-name: ItemsID
          items:
            type: string
            description: "id of item that belongs to list"
        date_created:
          type: string
          description: "date of creation"
          x-go-type: time.Time
        date_updated:
          type: string
          description: "date of last update"
          x-go-type: time.Time
      required:
        - id
        - user_id
        - name
        - private
        - favorite
        - completed
        - date_created
        
    Item:
      type: object
      properties:
        id: 
          type: string
          description: "item id"
          x-go-name: ID
        list_id: 
          type: string
          description: "item parent id"
          x-go-name: ListID
        name: 
          type: string
          description: "item name"
        description: 
          type: string
          description: "item description"
        address: 
          type: string
          description: "item address on map"
        point: 
          $ref: '#/components/schemas/Point'
        image_links:
          type: array
          description: "array of attached image links"
          items:
            type: string
            description: "image url"
        links:
          type: array
          description: "array of attached links"
          items:
            $ref: '#/components/schemas/Link'
        visited: 
          type: boolean
          description: "location is visited"
        date_created:
          type: string
          description: "creation date"
          x-go-type: time.Time
        date_updated:
          type: string
          description: "date of last update"
          x-go-type: time.Time
      required:
        - id
        - list_id
        - name
        - point
        - visited
        - date_created
        - date_updated

    Link:
      type: object
      description: "link object"
      properties:
        id: 
          type: string
          description: "link id"
          x-go-name: ID
        item_id: 
          type: string
          description: "link parent id"
          x-go-name: ItemID
        name: 
          type: string
          description: "link display name"
        url: 
          type: string
          description: "url"
          x-go-name: URL
      required:
        - id
        - item_id
        - url
    
    Point:
      type: object
      description: "item location on map"
      properties:
        id:
          type: string
          description: "location id"
          x-go-name: ID
        item_id:
          type: string
          description: "location parent id"
          x-go-name: ItemID
        lat:
          type: number
          description: "latitude of location on map"
          x-go-type: float64
        lng:
          type: number
          description: "longitude of location on map"
          x-go-type: float64
      required:
        - id
        - item_id
        - lat
        - lng

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: error message
        fields:
          type: object
          additionalProperties:
            type: string
      required:
        - error
