apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: travel
    component: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel
      component: haproxy
  template:
    metadata:
      labels:
        app: travel
        component: haproxy
    spec:
      hostNetwork: true
      initContainers:
      - name: init-volume
        image: haproxy-volume
        command: ["/bin/sh", "-c"]
        args:
          - cp /config/haproxy.cfg /config-volume/haproxy.cfg && cp /certs/* /certs-volume/
        volumeMounts:
          - name: haproxy-config-volume
            mountPath: /config-volume
          - name: haproxy-certs-volume
            mountPath: /certs-volume
        imagePullPolicy: IfNotPresent
      containers:
        - image: haproxy:2.8
          name: haproxy
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
          volumeMounts:
            - name: haproxy-config-volume
              mountPath: /usr/local/etc/haproxy/
            - name: haproxy-certs-volume
              mountPath: /etc/haproxy/certs/
          resources: {}
          imagePullPolicy: IfNotPresent
      volumes:
        - name: haproxy-config-volume
          emptyDir: {}
        - name: haproxy-certs-volume
          emptyDir: {}
      restartPolicy: Always
  type: LoadBalancer