apiVersion: v1
kind: PersistentVolume
metadata:
  name: haproxy-config-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./haproxy/config"
