apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  ports:
  - name: tempo
    port: 3101
    targetPort: 3101
  - name: tempo-grpc
    port: 4317
    targetPort: 4317
  selector:
    app: tempo
