apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.2.1
        args:
        - "-config.file=/etc/tempo/tempo.yaml"
        ports:
        - containerPort: 3101
          hostPort: 3101
          name: tempo-http
        - containerPort: 4317
          hostPort: 4317
          name: tempo-grpc
        volumeMounts:
        - name: tempo-config-volume
          mountPath: /etc/tempo
        - name: tempo-storage
          mountPath: /tmp/tempo
        resources: {}
      volumes:
      - name: tempo-config-volume
        configMap:
          name: tempo-config
      - name: tempo-storage
        emptyDir: {}
