BEGIN;

CREATE TABLE links (
  link_id UUID PRIMARY KEY,
  item_id UUID NOT NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

COMMIT;