kind: PersistentVolume
apiVersion: v1
metadata:
  name: loki-pv
  labels:
    app: travel
    component: travel-log-storage
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/loki"
    type: DirectoryOrCreate
