apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers: 
        - name: set-data-dir-permission
          image: alpine:3.18.2
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 10001:10001 /loki"]
          volumeMounts:
          - name: loki-storage
            mountPath: /loki
      containers:
        - name: loki
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
          image: grafana/loki:latest
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: loki-storage
              mountPath: /loki
          ports:
            - name: http
              containerPort: 3100
          resources: {}
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
