kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: travel
    component: travel-log-storage
  name: loki-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
