apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: travel
    component: travel-api-cache-volume
  name: travel-api-cache-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
