apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: travel
    component: travel-api-cache-volume
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/redis"
    type: DirectoryOrCreate
