apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: travel
    component: travel-api-cache-volume
  name: redis-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      pv-name: redis-pv-label
  resources:
    requests:
      storage: 512Mi
