// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package auth

import (
	"time"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error error message
	Error  string             `json:"error"`
	Fields *map[string]string `json:"fields,omitempty"`
}

// LoginUser defines model for LoginUser.
type LoginUser struct {
	// Email user email
	Email string `json:"email" validate:"required,email"`

	// Password user password
	Password string `json:"password" validate:"required"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// DateCreated date created
	DateCreated time.Time `json:"date_created"`

	// Email user's email
	Email string `json:"email"`

	// Id user unique id
	ID string `json:"id"`

	// Name user's name
	Name string `json:"name"`
}

// PostAuthLogoutJSONBody defines parameters for PostAuthLogout.
type PostAuthLogoutJSONBody = map[string]interface{}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginUser

// PostAuthLogoutJSONRequestBody defines body for PostAuthLogout for application/json ContentType.
type PostAuthLogoutJSONRequestBody = PostAuthLogoutJSONBody
