// Package image provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package image

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error error message
	Error  string             `json:"error"`
	Fields *map[string]string `json:"fields,omitempty"`
}

// PostImagesUploadListIDMultipartBody defines parameters for PostImagesUploadListID.
type PostImagesUploadListIDMultipartBody struct {
	// Images images to upload
	Images *[]openapi_types.File `json:"images,omitempty"`
}

// PostImagesUploadListIDMultipartRequestBody defines body for PostImagesUploadListID for multipart/form-data ContentType.
type PostImagesUploadListIDMultipartRequestBody PostImagesUploadListIDMultipartBody
