// Package image provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package image

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error error message
	Error  string             `json:"error"`
	Fields *map[string]string `json:"fields,omitempty"`
}

// PostImagesListIDMultipartBody defines parameters for PostImagesListID.
type PostImagesListIDMultipartBody struct {
	// Images images to upload
	Images *[]openapi_types.File `json:"images,omitempty"`
}

// PostImagesListIDMultipartRequestBody defines body for PostImagesListID for multipart/form-data ContentType.
type PostImagesListIDMultipartRequestBody PostImagesListIDMultipartBody
