apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: travel
    component: travel-api-db
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel
      component: travel-api-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: travel
        component: travel-api-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: travel
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:15.3
          name: travel-api-db
          ports:
            - containerPort: 5432
              hostPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: travel-api-db-volume
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      volumes:
        - name: travel-api-db-volume
          persistentVolumeClaim:
            claimName: travel-api-db-volume
