apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: travel
    component: travel-api-db-volume
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
    type: DirectoryOrCreate
